### ISSUE TITLE
Run command on mobile

### ISSUE THREAD

**Issue by Flintex6** [dwisyafriadi2/toncgpt#1]
Hi there, i checked your youtube video about tapcgpt, but i don't quite understand it, can you help with the termux command to run for mobile?

**Comment by dwisyafriadi2** [comment]
It's same with linux command

**Comment by dwisyafriadi2** [comment]
> Hi there, i checked your youtube video about tapcgpt, but i don't quite understand it, can you help with the termux command to run for mobile?

Same with command linux. 

git clone https://github.com/dwisyafriadi2/toncgpt.git
cd toncgpt
python3 run_toncgpt.py

first input your query on data.txt

**Comment by Flintex6** [comment]
I tried it, still same result
Kindly give me your telegram id, i'll be able to share pictures of my progress, you can put me through better, thanks boss🙏

**Comment by Flintex6** [comment]
![image](https://github.com/user-attachments/assets/fbf6f969-6d1c-4eca-9bf4-5bb965b274cb)

I keep getting this

**Comment by dwisyafriadi2** [comment]
> ![image](https://private-user-images.githubusercontent.com/187638882/390804247-fbf6f969-6d1c-4eca-9bf4-5bb965b274cb.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NDI1NjYsIm5iZiI6MTczMjk0MjI2NiwicGF0aCI6Ii8xODc2Mzg4ODIvMzkwODA0MjQ3LWZiZjZmOTY5LTZkMWMtNGVjYS05YmY0LTViYjk2NWIyNzRjYi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMzBUMDQ1MTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjY0ODVjNGRlYzE4MjY4MDhlMjcxMjU4YmQ3OGJhOGFhNmQyZjdiMmI3MmZlZjlhOGIxNjg2NjI1OTRmYjY3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.B23b-NQmiXVSMTCOswloKvlmPIXwyDYDFhxAI5Y4Rmg)
> 
> I keep getting this

try ``pip install cryptography`` or ``pip3 install cryptography``
